version: '3.1'
services:
  db:
    image: postgres

  web1:
    image: release_image
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      ENV_TAG: web_container_qa

  web2:
    image: release_image
    ports:
      - "4001:4000"
    depends_on:
      - db
    environment:
      ENV_TAG: web_container_demo

  web3:
    image: release_image
    ports:
      - "4002:4000"
    depends_on:
      - db
    environment:
      ENV_TAG: web_container_prod
